openapi: "3.0.0"

info:
  description: Register User
  version: 1.0.0
  title: Register User
  contact:
    name: Kirill B.
    url: kiryuxa.com
    email: baskirill.an@gmail.com
servers:
  - url: http://localhost:{port}/{basePath}
    description: Local server (uses local data)
    variables:
      port:
        default: "8080"
        enum:
          - "8080"
          - "8000"
      basePath:
        default: "api"

tags:
  - name: user
    description: Everything about user

paths:
  /registration:
    post:
      description: Register User
      summary: User Registration
      operationId: userRegistration
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegistrationRequest"
        required: true
      responses:
        "200":
          description: User Registration
          content:
            application/json:
              schema:
                type: object
        default:
          description: server error
          content:
            application/json:
              schema:
                $ref: "./../common/ServerError.yml#/components/schemas/ServerError"

components:
  schemas:
    RegistrationRequest:
      type: object
      required: [full_name, login, password]
      properties:
        full_name:
          type: string
        login:
          type: string
        password:
          type: string
