openapi: "3.0.0"  # openApiGenerate gradle task do not support officially 3.1.0 openapi version

info:
  description: Edit Instrument
  version: 1.0.0
  title: Edit Instrument
  contact:
    name: Kirill B
    email: baskirill.an@gmail.com
servers:
  - url: http://localhost:{port}/{basePath}
    description: Local server (uses local data)
    variables:
      port:
        default: "8080"
        enum:
          - "8080"
          - "8000"
      basePath:
        default: "api"

tags:
  - name: editInstrument
    description: Edit Instrument

paths:
  /instrument/edit:
    post:
      description: Edit Instrument
      summary: Edit Instrument
      operationId: editInstrument
      tags:
        - editInstrument
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditInstrumentRequestBody'
        required: true
      responses:
        "200":
          description: Instrument Types
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Client Error
          content:
            application/json:
              schema:
                $ref: "./../common/ClientError.yml#/components/schemas/ClientError"
        default:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "./../common/ServerError.yml#/components/schemas/ServerError"

components:
  schemas:
    EditInstrumentRequestBody:
      type: object
      required: [ instrument_name, instrument_type, manufacturer_name, manufacturer_date,release_date,country, materials ]
      properties:
        instrument_id:
          $ref: "./../common/InstrumentId.yml#/components/schemas/InstrumentId"
        instrument_name:
          type: string
        instrument_type:
          type: string
        manufacturer_name:
          type: string
        manufacturer_date:
          type: string
          format: date
        release_date:
          type: string
          format: date
        country:
          type: string
        materials:
          type: array
          items:
            type: string
