openapi: "3.0.0"

info:
  version: 1.0.0
  title: Get Instrument By ID
servers:
  - url: http://localhost:8080/

paths:
  /api/instrument/{instrumentId}:
    get:
      summary: Get Instrument by ID
      operationId: getInstrumentById
      tags:
        - getInstrumentById
      parameters:
        - name: instrumentId
          in: path
          required: true
          description: Instrument ID
          schema:
            type: string
      responses:
        "200":
          description: Instrument Detail
          content:
            application/json:
              schema:
                $ref: "./components/InstrumentDetail.yml#/components/schemas/InstrumentDetail"
        "500":
          description: server error
          content:
            application/json:
              schema:
                $ref: "./../common/ServerError.yml#/components/schemas/ServerError"
