openapi: "3.0.0"  # openApiGenerate gradle task do not support officially 3.1.0 openapi version

info:
  description: Get Instrument Basic Materials
  version: 1.0.0
  title: Get Instrument Basic Materials
  contact:
    name: Kirill B
    email: baskirill.an@gmail.com
servers:
  - url: http://localhost:{port}/{basePath}
    description: Local server (uses local data)
    variables:
      port:
        default: "8080"
        enum:
          - "8080"
          - "8000"

tags:
  - name: getInstrumentBasicMaterials
    description: Get Instrument Basic Materials

paths:
  /api/instrument/materials:
    get:
      description: Get Instrument Basic Materials
      summary: Get Instrument Basic Materials
      operationId: getInstrumentBasicMaterials
      tags:
        - getInstrumentBasicMaterials
      responses:
        "200":
          description: Instrument Basic Materials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetInstrumentBasicMaterialsResponse"
        "400":
          description: Client Error
          content:
            application/json:
              schema:
                $ref: "./../common/ClientError.yml#/components/schemas/ClientError"
        default:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "./../common/ServerError.yml#/components/schemas/ServerError"

components:
  schemas:
    GetInstrumentBasicMaterialsResponse:
      type: object
      required: [content]
      properties:
        content:
          type: array
          items:
            $ref: "./../common/BasicMaterial.yml#/components/schemas/BasicMaterial"
