openapi: "3.0.0"

info:
  description: Get Instrument by ID
  version: 1.0.0
  title: Get Instrument by ID
  contact:
    name: Kirill B.
    url: kiryuxa.com
    email: baskirill.an@gmail.com
servers:
  - url: http://localhost:{port}/{basePath}
    description: Local server (uses local data)
    variables:
      port:
        default: "8080"
        enum:
          - "8080"
          - "8000"
      basePath:
        default: "api"

tags:
  - name: instrument
    description: Everything about instrument

paths:
  /instrument/{instrumentId}:
    get:
      description: Get Instrument by ID
      summary: Get Instrument by ID
      operationId: getInstrumentById
      tags:
        - instrument
      parameters:
        - name: instrumentId
          in: path
          required: true
          description: Instrument ID
          schema:
            type: string
      responses:
        "200":
          description: Instrument Detail
          content:
            application/json:
              schema:
                $ref: "./components/InstrumentDetail.yml#/components/schemas/InstrumentDetail"
        "400":
          description: Client Error
          content:
            application/json:
              schema:
                $ref: "./../common/ClientError.yml#/components/schemas/ClientError"
        default:
          description: server error
          content:
            application/json:
              schema:
                $ref: "./../common/ServerError.yml#/components/schemas/ServerError"
