openapi: "3.0.0"

info:
  version: 1.0.0
  title: Get Instruments by Criteria
servers:
  - url: http://localhost:8080/

paths:
  /api/instruments:
    post:
      summary: Get Instruments by Criteria
      operationId: getInstrumentsByCriteria
      tags:
        - getInstrumentsByCriteria
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./components/GetInstrumentByCriteriaRequestBody.yml#/components/schemas/GetInstrumentCriteriaRequestBody"
        required: true
      responses:
        "200":
          description: Instrument Details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetInstrumentsByCriteriaResponse"
        default:
          description: server error
          content:
            application/json:
              schema:
                $ref: "./../common/ServerError.yml#/components/schemas/ServerError"

components:
  schemas:
    GetInstrumentsByCriteriaResponse:
      type: object
      required: [ content ]
      properties:
        content:
          type: array
          items:
            $ref: './components/InstrumentDetail.yml#/components/schemas/InstrumentDetail'
