openapi: "3.0.0"

info:
  description: Basic Login
  version: 1.0.0
  title: Basic Login
  contact:
    name: Kirill B.
    url: kiryuxa.com
    email: baskirill.an@gmail.com
servers:
  - url: http://localhost:{port}/{basePath}
    description: Local server (uses local data)
    variables:
      port:
        default: "8080"
        enum:
          - "8080"
          - "8000"
      basePath:
        default: "api"

tags:
  - name: user
    description: Everything about user

paths:
  /auth/login:
    post:
      description: Basic Authentication
      summary: Basic Login
      operationId: basicLogin
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsernameAndPasswordRequestBody"
        required: true
      responses:
        "200":
          description: Profile Details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JwtResponse"
        default:
          description: server error
          content:
            application/json:
              schema:
                $ref: "./../common/ServerError.yml#/components/schemas/ServerError"

components:
  schemas:
    UsernameAndPasswordRequestBody:
      type: object
      required: [ username, password ]
      properties:
        username:
          type: string
        password:
          type: string

    JwtResponse:
      type: object
      required: [ jwt ]
      properties:
        jwt:
          type: string