openapi: "3.0.0"

info:
  description: Get Profile
  version: 1.0.0
  title: Get Profile
  contact:
    name: Kirill B.
    url: kiryuxa.com
    email: baskirill.an@gmail.com
servers:
  - url: http://localhost:{port}/{basePath}
    description: Local server (uses local data)
    variables:
      port:
        default: "8080"
        enum:
          - "8080"
          - "8000"
      basePath:
        default: "api"

tags:
  - name: profile
    description: Everything about user profile

paths:
  /profile:
    get:
      description: Get User Profile
      summary: Get Profile Info
      operationId: getProfile
      tags:
        - profile
      responses:
        "200":
          description: Profile Details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileDetailsResponse"
        default:
          description: server error
          content:
            application/json:
              schema:
                $ref: "./../common/ServerError.yml#/components/schemas/ServerError"

components:
  schemas:
    ProfileDetailsResponse:
      type: object
      required: [username, role, full_name]
      properties:
        username:
          type: string
        role:
          type: string
        full_name:
          type: string
