openapi: "3.0.0" # openApiGenerate gradle task do not support officially 3.1.0 openapi version

info:
  description: Basic Material
  version: 1.0.0
  title: Country
  contact:
    name: Kirill B
    email: baskirill.an@gmail.com

paths: {}

components:
  schemas:
    BasicMaterial:
      type: object
      required: [i18n_code]
      properties:
        i18n_code:
          type: string
          example: "material.type.wood"
        localized_text:
          type: string
          example: "Wood"
