# spectral-disable oas3-unused-component
openapi: "3.0.0"

info:
  description: Client Error
  version: 1.0.0
  title: Client Error
  contact:
    name: Kirill B.
    url: kiryuxa.com
    email: baskirill.an@gmail.com
servers:
  - url: http://localhost:{port}/{basePath}
    description: Local server (uses local data)
    variables:
      port:
        default: "8080"
        enum:
          - "8080"
          - "8000"
      basePath:
        default: "api"

paths: {}

components:
  schemas:
    ClientError:
      type: object
      required: [message]
      properties:
        message:
          type: string
          description: Error description
      example:
        message: "Client Error"
