openapi: "3.0.0" # openApiGenerate gradle task do not support officially 3.1.0 openapi version

info:
  description: Client Error
  version: 1.0.0
  title: Client Error
  contact:
    name: Kirill B
    email: baskirill.an@gmail.com

paths: {}

components:
  schemas:
    ClientError:
      type: object
      required: [message]
      properties:
        message:
          type: string
          description: Error description
      example:
        message: "Client Error"
