openapi: "3.0.0"  # openApiGenerate gradle task do not support officially 3.1.0 openapi version

info:
  description: Instrument Details
  version: 1.0.0
  title: Instrument Details
  contact:
    name: Kirill B
    email: baskirill.an@gmail.com

paths: {}

components:
  schemas:
    InstrumentDetail:
      type: object
      required: [ id, name, type, manufacturer, manufacturer_date, release_date, country, basic_materials]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
        manufacturer:
          type: string
        manufacturer_date:
          type: string
        release_date:
          type: string
        country:
          type: string
        basic_materials:
          type: array
          items:
            type: string
