openapi: "3.0.0" # openApiGenerate gradle task do not support officially 3.1.0 openapi version

info:
  description: Instrument Details
  version: 1.0.0
  title: Instrument Details
  contact:
    name: Kirill B
    email: baskirill.an@gmail.com

paths: {}

components:
  schemas:
    InstrumentDetail:
      type: object
      required:
        [
          instrument_id,
          instrument_name,
          instrument_type,
          manufacturer_name,
          manufacturer_date,
          release_date,
          country,
          basic_materials,
        ]
      properties:
        instrument_id:
          $ref: "./../common/InstrumentId.yml#/components/schemas/InstrumentId"
        instrument_name:
          $ref: "./../common/InstrumentName.yml#/components/schemas/InstrumentName"
        instrument_type:
          $ref: "./../common/InstrumentType.yml#/components/schemas/InstrumentType"
        manufacturer_name:
          $ref: "./../common/ManufacturerName.yml#/components/schemas/ManufacturerName"
        manufacturer_date:
          $ref: "./../common/ManufactureDate.yml#/components/schemas/ManufactureDate"
        release_date:
          $ref: "./../common/ReleaseDate.yml#/components/schemas/ReleaseDate"
        country:
          $ref: "./../common/Country.yml#/components/schemas/Country"
        basic_materials:
          type: array
          items:
            $ref: "./../common/BasicMaterial.yml#/components/schemas/BasicMaterial"
