openapi: "3.0.0" # openApiGenerate gradle task do not support officially 3.1.0 openapi version

info:
  description: Instrument Type
  version: 1.0.0
  title: Instrument Details
  contact:
    name: Kirill B
    email: baskirill.an@gmail.com

paths: {}

components:
  schemas:
    InstrumentTypeCode:
      type: string
      example: STRINGED

    InstrumentType:
      type: object
      required: [i18n_code]
      properties:
        i18n_code:
          $ref: "#/components/schemas/InstrumentTypeCode"
        localized_text:
          type: string
          example: Stringed
