openapi: "3.0.0"  # openApiGenerate gradle task do not support officially 3.1.0 openapi version

info:
  description: Instrument Details
  version: 1.0.0
  title: Instrument Details
  contact:
    name: Kirill B
    email: baskirill.an@gmail.com

paths: {}

components:
  schemas:
    InstrumentId:
      type: integer
      format: int64
