openapi: "3.0.0" # openApiGenerate gradle task do not support officially 3.1.0 openapi version

info:
  description: Manufacturer Name
  version: 1.0.0
  title: Manufacturer Name
  contact:
    name: Kirill B
    email: baskirill.an@gmail.com

paths: {}

components:
  schemas:
    ManufacturerName:
      type: object
      required: [manufacturer_name]
      properties:
        manufacturer_name:
          type: string
          example: "STRINGED"
