openapi: "3.1.0"

info:
  description: Server Error
  version: 1.0.0
  title: Server Error
  contact:
    name: Kirill B
    email: baskirill.an@gmail.com

paths: {}

components:
  schemas:
    ServerError:
      type: object
      required: [message]
      properties:
        message:
          type: string
          description: A description of the error.
      example:
        message: "Internal Server Error. Please try again later."
