openapi: "3.0.0"

info:
  title: Server Error
  version: 1.0.0

paths: {}

components:
  schemas:
    ServerError:
      type: object
      properties:
        message:
          type: string
          description: A description of the error.
      required:
        - message
      example:
        message: "Internal Server Error. Please try again later."
