openapi: "3.0.0" # openApiGenerate gradle task do not support officially 3.1.0 openapi version

info:
  description: Get Instruments Request Body
  version: 1.0.0
  title: Get Instruments Request Body
  contact:
    name: Kirill B
    email: baskirill.an@gmail.com

paths: {}

components:
  schemas:
    GetInstrumentsByCriteriaRequestBody:
      type: object
      properties:
        instrument_name:
          # https://stackoverflow.com/questions/40920441/how-to-specify-a-property-can-be-null-or-a-reference-with-swagger
          nullable: true
          allOf:
            - $ref: "./../../common/InstrumentName.yml#/components/schemas/InstrumentName"
        instrument_types:
          nullable: true
          type: array
          items:
            $ref: "./../../common/InstrumentType.yml#/components/schemas/InstrumentType"
        manufacturer_names:
          nullable: true
          type: array
          items:
            $ref: "./../../common/ManufacturerName.yml#/components/schemas/ManufacturerName"
        manufacture_date_from:
          nullable: true
          allOf:
            - $ref: "./../../common/ManufactureDate.yml#/components/schemas/ManufactureDate"
        manufacture_date_to:
          nullable: true
          allOf:
            - $ref: "./../../common/ManufactureDate.yml#/components/schemas/ManufactureDate"
        release_date_from:
          nullable: true
          allOf:
            - $ref: "./../../common/ReleaseDate.yml#/components/schemas/ReleaseDate"
        release_date_to:
          nullable: true
          allOf:
            - $ref: "./../../common/ReleaseDate.yml#/components/schemas/ReleaseDate"
        countries:
          nullable: true
          type: array
          items:
            $ref: "./../../common/Country.yml#/components/schemas/Country"
        materials:
          nullable: true
          type: array
          items:
            $ref: "./../../common/BasicMaterial.yml#/components/schemas/BasicMaterial"
        instrument_ids:
          nullable: true
          type: array
          items:
            $ref: "./../../common/InstrumentId.yml#/components/schemas/InstrumentId"
