# spectral-disable oas3-unused-component
openapi: "3.0.0"

info:
  description: Instrument Details
  version: 1.0.0
  title: Instrument Details
  contact:
    name: Kirill B.
    url: kiryuxa.com
    email: baskirill.an@gmail.com
servers:
  - url: http://localhost:{port}/{basePath}
    description: Local server (uses local data)
    variables:
      port:
        default: "8080"
        enum:
          - "8080"
          - "8000"
      basePath:
        default: "api"

paths: {}

components:
  schemas:
    InstrumentDetail:
      type: object
      required: [ id, name, type, manufacturer, manufacturerDate, releaseDate, country, basicMaterials]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
        manufacturer:
          type: string
        manufacturer_date:
          type: string
        release_date:
          type: string
        country:
          type: string
        basic_materials:
          type: array
          items:
            type: string
