openapi: "3.0.0"  # openApiGenerate gradle task do not support officially 3.1.0 openapi version

info:
  description: List Favorite
  version: 1.0.0
  title: List Favorite
  contact:
    name: Kirill B
    email: baskirill.an@gmail.com
servers:
  - url: http://localhost:{port}/{basePath}
    description: Local server (uses local data)
    variables:
      port:
        default: "8080"
        enum:
          - "8080"
          - "8000"

tags:
  - name: listFavorite
    description: List Favorite

paths:
  /api/favorite/list:
    get:
      description: List Favorite
      summary: List Favorite
      operationId: listFavorite
      tags:
        - listFavorite
      responses:
        "200":
          description: Instrument Details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListFavoriteResponseBody"
        "400":
          description: Client Error
          content:
            application/json:
              schema:
                $ref: "./../common/ClientError.yml#/components/schemas/ClientError"
        default:
          description: server error
          content:
            application/json:
              schema:
                $ref: "./../common/ServerError.yml#/components/schemas/ServerError"

components:
  schemas:
    ListFavoriteResponseBody:
      type: object
      required: [content]
      properties:
        content:
          type: array
          items:
            $ref: "./../common/InstrumentDetail.yml#/components/schemas/InstrumentDetail"
