openapi: "3.1.0"

info:
  description: Remove Favorite
  version: 1.0.0
  title: Remove Favorite
  contact:
    name: Kirill B
    email: baskirill.an@gmail.com
servers:
  - url: http://localhost:{port}/{basePath}
    description: Local server (uses local data)
    variables:
      port:
        default: "8080"
        enum:
          - "8080"
          - "8000"
      basePath:
        default: "api"

tags:
  - name: removeFavorite
    description: Remove Favorite

paths:
  /favorite/remove:
    post:
      description: Remove Favorite
      summary: Remove Favorite
      operationId: removeFavorite
      tags:
        - removeFavorite
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RemoveFavoriteRequestBody"
        required: true
      responses:
        "200":
          description: Instrument Details
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Client Error
          content:
            application/json:
              schema:
                $ref: "./../common/ClientError.yml#/components/schemas/ClientError"
        default:
          description: server error
          content:
            application/json:
              schema:
                $ref: "./../common/ServerError.yml#/components/schemas/ServerError"

components:
  schemas:
    RemoveFavoriteRequestBody:
      type: object
      required: [instrument_id]
      properties:
        instrument_id:
          type: number
          format: int64
