networks:
  muse:
    driver: bridge

services:
  server:
    image: muse-server:latest
    container_name: muse-server
    ports:
      - ${SERVER_PORT}:8080
    networks:
      - muse

  client:
    image: muse-client:latest
    container_name: muse-client
    ports:
      - ${CLIENT_PORT}:80
    networks:
      - muse
