name: CI + CD

on: [pull_request]

jobs:
  assign_me:
    runs-on: ubuntu-22.04
    name: "[PR] Assign me"
    steps:
      - uses: AlbertHernandez/assign-me@v1.0.0
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
