name: CI

on: [ push ]

# [ ] Проверить зависимости при помощи OWASP Dependency Check
# 4. Собрать docker образ
# 5. Подключиться по SSH до dev.muse.kiryuxa.com
# 6. Поднять докер контейнер на порту + поменять реверс проксю чтобы перекидывало с dev.muse.kiryuxa.com -> localhost:59195
# Готово!

# TODO(speed-up): не прогонять линтеры и статанализаторы если исходный код не менялся
# TODO(speed-up): не включать каждый раз gradle daemon
# TODO(staging): if: github.event.ref == "refs/heads/main"

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-22.04
    steps:
      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.0'

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run linter
        run: ./tools/scripts/runLinter.sh

  static-analyzer:
    name: Static Analyzer
    runs-on: ubuntu-22.04
    steps:
      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.0'

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run static analyzer
        run: ./tools/scripts/runStaticAnalyzer.sh

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.0'

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Unit Tests
        run: ./tools/scripts/runUnitTests.sh

      - name: Publish Unit Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v1.9
        with:
          files: ./**/**/build/test-results/**/*.xml
          report_individual_runs: true

      - name: Gather reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: ./**/**/build/reports

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-22.04
    needs: [ "linter", "static-analyzer", "unit-tests" ]
    environment:
      name: dev
      url: http://dev.muse.kiryuxa.com
    steps:
      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.0'

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub via token
        run: docker login -u myshx -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Server Docker Image
        run: |
          ./tools/scripts/buildJar.sh
          docker build . -t "myshx/muse-server:dev-${{ github.sha }}"

      - name: Push Server Docker Image
        run: docker push "myshx/muse-server:dev-${{ github.sha }}"

      - name: Run server at home lab
        uses: appleboy/ssh-action@v1.0.3
        env:
          GIT_COMMIT_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          envs: GIT_COMMIT_SHA
          script: |
            export GIT_COMMIT_SHA=$GIT_COMMIT_SHA
            docker stop "muse-server:dev-$GIT_COMMIT_SHA"
            docker rm "muse-server:dev-$GIT_COMMIT_SHA"
            docker rmi "muse-server:dev-$GIT_COMMIT_SHA"
            docker run -d -p 50505:8080 "myshx/muse-server:dev-$GIT_COMMIT_SHA"
